import { COMMON_WIN32_ABI } from '../../vm86/abi';

/**
 * Independent x86 ABI for Red Alert 2 / lightweight XWIS clients.
 *
 * Networking, outer WOL UI, and Bink use minimal failure/skip semantics during single-player startup, but correct ret n values remain essential: one optional-feature probe can otherwise permanently corrupt the guest stack. XWIS ord1 exports only ?X@@YAXXZ, a no-argument cdecl function, so its cleanup size is 0. Stack-cleanup sizes shared with War3 live in COMMON_WIN32_ABI; this table keeps only RA2 additions.
 */
export const RA2_ABI: Record<string, number> = {
  ...COMMON_WIN32_ABI,
  'XWIS.DLL!ord1': 0,

  'KERNEL32.DLL!FlushInstructionCache': 12,
  'KERNEL32.DLL!VirtualProtect': 16,
  'KERNEL32.DLL!EscapeCommFunction': 8,
  'KERNEL32.DLL!ClearCommBreak': 4,
  'KERNEL32.DLL!SetCommBreak': 4,
  'KERNEL32.DLL!FileTimeToDosDateTime': 12,
  'KERNEL32.DLL!GetFileInformationByHandle': 8,
  'KERNEL32.DLL!lstrcpyA': 8,
  'KERNEL32.DLL!ClearCommError': 12,
  'KERNEL32.DLL!GetCommState': 8,
  'KERNEL32.DLL!PurgeComm': 8,
  'KERNEL32.DLL!SetupComm': 12,
  'KERNEL32.DLL!GetCommMask': 8,
  'KERNEL32.DLL!GetCommModemStatus': 8,
  'KERNEL32.DLL!GetOverlappedResult': 16,
  'KERNEL32.DLL!GetCurrentDirectoryA': 8,
  'KERNEL32.DLL!DosDateTimeToFileTime': 12,
  'KERNEL32.DLL!FreeConsole': 0,
  'KERNEL32.DLL!AllocConsole': 0,
  'KERNEL32.DLL!MapViewOfFileEx': 24,
  'KERNEL32.DLL!SetCommTimeouts': 8,
  'KERNEL32.DLL!SetCommState': 8,
  'KERNEL32.DLL!PeekConsoleInputA': 16,
  'KERNEL32.DLL!SetConsoleMode': 8,
  'KERNEL32.DLL!lstrlenW': 4,
  'KERNEL32.DLL!ReadConsoleInputA': 16,
  'KERNEL32.DLL!GetNumberOfConsoleInputEvents': 8,
  'KERNEL32.DLL!WriteConsoleA': 20,
  'KERNEL32.DLL!HeapValidate': 12,
  'KERNEL32.DLL!DebugBreak': 0,

  'USER32.DLL!ToAscii': 20,
  'USER32.DLL!ChildWindowFromPointEx': 16,
  'USER32.DLL!GetAsyncKeyState': 4,
  'USER32.DLL!DialogBoxParamA': 20,
  'USER32.DLL!DialogBoxIndirectParamA': 20,
  'USER32.DLL!MapVirtualKeyA': 8,
  'USER32.DLL!MoveWindow': 24,
  'USER32.DLL!GetCapture': 0,
  'USER32.DLL!ValidateRect': 8,
  'USER32.DLL!AdjustWindowRect': 12,
  'USER32.DLL!IsDlgButtonChecked': 8,
  'USER32.DLL!CheckDlgButton': 12,
  'USER32.DLL!WaitForInputIdle': 8,
  'USER32.DLL!RedrawWindow': 16,
  'USER32.DLL!GetWindowContextHelpId': 4,
  'USER32.DLL!WinHelpA': 16,
  'USER32.DLL!ChildWindowFromPoint': 12,
  'USER32.DLL!FindWindowA': 8,
  'USER32.DLL!GetKeyNameTextA': 12,
  'USER32.DLL!LockWindowUpdate': 4,
  'USER32.DLL!CloseWindow': 4,
  'USER32.DLL!MessageBoxIndirectA': 4,
  'USER32.DLL!GetUpdateRect': 12,
  'USER32.DLL!BringWindowToTop': 4,
  'USER32.DLL!EnumChildWindows': 12,
  'USER32.DLL!CharToOemBuffA': 12,
  'USER32.DLL!GetNextDlgTabItem': 12,
  'USER32.DLL!RegisterHotKey': 16,

  'GDI32.DLL!GetTextColor': 4,
  'GDI32.DLL!GetBkMode': 4,
  'GDI32.DLL!DPtoLP': 12,
  'GDI32.DLL!SetWindowOrgEx': 16,
  'GDI32.DLL!RestoreDC': 8,
  'GDI32.DLL!ModifyWorldTransform': 12,
  'GDI32.DLL!SetGraphicsMode': 8,
  'GDI32.DLL!SetViewportOrgEx': 16,
  'GDI32.DLL!SaveDC': 4,
  'GDI32.DLL!CreateDIBSection': 24,

  'OLE32.DLL!StgCreateDocfile': 16,
  'OLE32.DLL!CoRevokeClassObject': 4,
  'OLE32.DLL!OleUninitialize': 0,
  'OLE32.DLL!OleInitialize': 4,
  'OLE32.DLL!CoRegisterClassObject': 20,
  'OLE32.DLL!CoDisconnectObject': 8,
  'OLE32.DLL!StgOpenStorage': 24,
  'OLE32.DLL!CoFileTimeNow': 4,
  'OLE32.DLL!StringFromCLSID': 8,
  'OLE32.DLL!CLSIDFromString': 8,
  // OleSaveToStream(IPersistStream*, IStream*) has only two arguments. Registering
  // 12 bytes makes the stdcall stub pop one extra slot; when RA2 saves ALL01T's initial state after campaign selection,
  // the return address becomes data, eventually producing WASM unreachable.
  'OLE32.DLL!OleSaveToStream': 8,
  'OLE32.DLL!OleLoadFromStream': 12,
  'OLE32.DLL!OleRun': 4,

  'OLEAUT32.DLL!ord200': 8,
  'OLEAUT32.DLL!ord34': 8,
  'OLEAUT32.DLL!ord161': 8,
  'OLEAUT32.DLL!ord6': 4,
  'OLEAUT32.DLL!ord2': 4,
  'OLEAUT32.DLL!ord33': 16,
  'OLEAUT32.DLL!ord201': 8,
  'OLEAUT32.DLL!ord12': 16,
  'OLEAUT32.DLL!ord202': 4,
  'OLEAUT32.DLL!ord9': 4,
  'OLEAUT32.DLL!ord8': 4,

  'WSOCK32.DLL!ord7': 20,
  'WSOCK32.DLL!ord14': 4,
  'WSOCK32.DLL!ord9': 4,
  'WSOCK32.DLL!ord17': 24,
  'WSOCK32.DLL!ord8': 4,
  'WSOCK32.DLL!ord21': 20,
  'WSOCK32.DLL!ord20': 24,
  'WSOCK32.DLL!ord15': 4,
  'WSOCK32.DLL!ord57': 8,
  'WSOCK32.DLL!ord115': 8,
  'WSOCK32.DLL!ord1111': 12,
  'WSOCK32.DLL!ord101': 16,
  'WSOCK32.DLL!ord116': 0,
  'WSOCK32.DLL!ord111': 0,
  'WSOCK32.DLL!ord11': 4,
  'WSOCK32.DLL!ord23': 12,
  'WSOCK32.DLL!ord2': 12,
  'WSOCK32.DLL!ord3': 4,
  'WSOCK32.DLL!ord52': 4,

  'COMCTL32.DLL!ord17': 0,
  'IMM32.DLL!ImmSetOpenStatus': 8,

  'BINKW32.DLL!_BinkSetSoundSystem@8': 8,
  'BINKW32.DLL!_BinkOpenDirectSound@4': 4,
  'BINKW32.DLL!_BinkGetError@0': 0,
  'BINKW32.DLL!_BinkOpen@8': 8,
  'BINKW32.DLL!_BinkSetVolume@8': 8,
  'BINKW32.DLL!_BinkClose@4': 4,
  'BINKW32.DLL!_BinkDDSurfaceType@4': 4,
  'BINKW32.DLL!_BinkGoto@12': 12,
  'BINKW32.DLL!_BinkPause@8': 8,
  'BINKW32.DLL!_BinkNextFrame@4': 4,
  'BINKW32.DLL!_BinkCopyToBuffer@28': 28,
  'BINKW32.DLL!_BinkDoFrame@4': 4,
  'BINKW32.DLL!_BinkWait@4': 4,

  'WINMM.DLL!waveOutRestart': 4,
  'WINMM.DLL!waveOutSetVolume': 8,
  'WINMM.DLL!waveOutPause': 4,
};

export function ra2Win32ArgBytes(dll: string, name: string): number {
  const key = `${dll.toUpperCase()}!${name}`;
  const bytes = RA2_ABI[key];
  if (bytes === undefined) throw new Error(`未登记的 Red Alert 2 Win32 ABI: ${key}`);
  return bytes;
}
